[workspace]
members = ["app", "page", "pages/*"]
default-members = ["app"]

[workspace.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
rev = "ece17c8d62a06809f61233fef81ad7bd5404399d"
default-features = false
features = ["debug", "winit", "dyrend", "tokio"]
